DROP DATABASE IF EXISTS theater;
CREATE DATABASE theater;
USE theater;

-- CREATE TABLES;

CREATE TABLE theater(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
city VARCHAR(100) NOT NULL,
UNIQUE(name,city)
);

